---
output: html_document
editor_options:
  chunk_output_type: console
---

# Alie's Programs {#alies_programs}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```

The following programs are available to members of the EAS department. Contact me for more info!

## Writing Support {-}

Once each week, I have a slot of ~4 hours which I can dedicate towards helping a department member with a scientific communication task/project. 

When you "book" the slot, you get up to 4 hours of my time that week, and we can use that time in whatever way would be most beneficial to you. 

So, for example, if you want edits on a paper, you could send me the draft, and I'll spend 3-4 hours reading it and putting in comments/edits, and then I can send it back to you, and we meet to discuss. Or, maybe you only want to meet to discuss some ideas or parts of a writing project that you're stuck on. Or, maybe you want to give a practice talk for a conference, and receive feedback about your presentation and slides. Basically, it's totally flexible, so think specifically about what you are hoping that I can help you with, and how best to structure up to 4 hours of time in order to achieve that. 

**Sign up** in the EAS department google calendar, look for a Wednesday morning "Scientific Writing Support with Alie" slot that doesn't yet have somebody's name in it. Replace "[Name]" with your name. 

By default, this slot is on Wednesday mornings, however, it can be moved if necessary! Sign up for the Wednesday slot to claim my time that week, but then contact me to sort out an alternative day/time.

**Reach out to me a day or two before your slot so that we can discuss your needs and strategize about how best to use the time!**

If you are working towards a tight deadline, and you need help before the next available slot, contact me! I can often be flexible and give you time sooner if necessary.  
  
  
  
## Writing Solidarity Club {-}

*Note: This program is on hold until further notice. If you are interested in this program, please contact me directly to let me know!*

Lots of writing to do, but can't find the motivation? Need extra incentive to block off writing time? Come to Writing Solidarity Club! Bring your laptop and leave your over-active inner-critic behind! It's writing time!

Every Tuesday, from 14:30 to 16:30, I will be writing in Bückle room 4.06 (the conference room next to MPI-AB reception). Anybody is welcome to join! No sign up required.  
  
  
  
## Writing Retreat {-}

Writing retreats are an opportunity for department members to enjoy a change of pace and scenery, and devote some quality time to writing up their science in a collective and supportive environment.

Each day at a Retreat, we set our goals in the morning, write independently together in a conference room throughout the day, and then reflect/check-in on our progress in the evenings. Breakfast, lunch, and dinner are provided, as well as 2 coffee breaks each day. Participants are also welcome to plan/lead group activities (e.g. walks/hikes/jogs around the area, movie nights, yoga sessions, etc), and take alone time as they need.

To get the most out of a Retreat, we want participants to arrive ready to write, which involves some preparatory work ahead of time. About 6 weeks before a Retreat, I’ll check-in with each participant and we’ll discuss what they'll work on at the Retreat, where they are at in their writing preparation process, and further steps that they need to take before the Retreat (e.g. completing analyses, meeting with a collaborator or supervisor).

This fall, we will have our first EAS Writing Retreat at the [Hotel St Elisabeth Hegne](https://www.st-elisabeth-hegne.de/hotel-st-elisabeth.html) from November 21st to the 25th.

Applications are now closed and the final list of participants has been notified!
 
***Stay tuned for info about or next EAS Writing Retreat, which will take place in Spring 2023!***
  
  
  
## Writing Workshop {-}

Stay tuned for more information!