---
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```

# Blog {#blog_main}

## [Proper Paragraphing](#Paragraphs) {-}

Paragraphs can be thought of as the basic building blocks of a text. Proper paragraphing is vital in scientific writing: if an author hasn't properly 'chunked' their writing, then the audience can't properly 'chunk' their reading and interpretation. In this post, I go over the basic tenants of effective paragraphing and effective paragraphs.

## [Scientific Writing in the EAS Dept](#EASslides) {-}

Here, you can see my slides (& discussion notes) from the workshop/discussion series about *Scientific Writing in the EAS Department* that took place during lab meetings on June 1st & 22nd, and October 19th, 2022. 


## [Styles in MS Word](#WordStyles) {-}

If you don't already use *Styles* in Microsoft Word, I highly recommend it! Despite what the term suggests, the benefits of using *Styles* go far beyond just aesthetics. Using *Styles* allows you to easily see an overview of the organization of a text that you're writing, which can help you to work out structure and flow. In this post, I go over the ***Why*** and ***How*** of using *Styles* in MS Word.
  
    
    
## [A good title is a simple sticky statement](#Titles) {-}

Without a doubt, the part of your paper that will get read the most often, and by the widest audience, is your title. Ideally, your title will be successful at signalling to your primary intended audience that this paper is for them, as well as signalling to everybody what the main message of your paper is. In this post, I go over what makes for a good title.
  
  
  
## [All About Abstracts](#Abstracts) {-}

Here, you can learn about how to structure an abstract for an original research manuscript (bonus, some of this information also applies to review & other types of articles). 
  
  
  
## [Feedback Framework](#FF) {-}

How can we know if our scientific writing is effective? How can we know if our audience is deriving the correct meaning from our writing? How can we know if they are achieving this relatively quickly and painlessly? ***We can ask them!*** This post is all about giving and receiving feedback.
