---
output: html_document
editor_options:
  chunk_output_type: console

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```


# Perfecting the Scientific Poster {.unlisted .unnumbered #Posters}

Making a good poster for a scientific conference is no small feat. While people sometimes think of a poster as an "easy" alternative to a talk, making a good poster can actually be really tough! Most conferences (at least in animal behavior & ecology) have "poster sessions" - this is when you stand beside your poster and people walk around and look at the posters. If somebody is interested in your poster, then they'll talk to you about it! 

Because your poster is not meant to stand-alone and communicate your research without you, you should think of your poster not as a "visual version of a paper" but rather as a "presentation aide." As such, a good poster accomplishes 3 main goals: 1) it grabs people's attention, 2) it simply and quickly communicates the main point of a study, and 3) it facilitates a conversation between the poster presenter and their target audience members. 

There are many online resources to help you get started on making a poster, but here I will just go through some of the most important rules of poster making:

1) **Limit words!** Remember, the goal of the poster is *not* to communicate your *entire study* and all of it's nuances and methods and details to the audience! YOU will be standing by your poster, and so YOU can directly communicate with interested audience members and answer questions and give a more thorough explanation of your study. As such, stick to the ***main message***! Reduce your study to its main takeaway message, and then build your poster up from that. Think about the main components that go into an [abstract](#Abstracts), and be sure to hit these (but not a whole lot more) on your poster. (Note: Unlike an abstract, however, your poster should be properly cited and have basic acknowledgements (at least major funders and institutional support).)

2) **Make use of visuals!** Whenever possible, trade words for graphics! Use a conceptual figure or flow-chart diagram to show links between concepts, present your results as figures rather than text, incorporate photos or diagrams of your study system or experimental set up, etc. Think about what visuals would be helpful for you to have on hand to point at when you are explaining your study to passers by, and incorporate these.

3) **Check your font sizes!** You want people to be able to read your poster from at least 2 meters away - this way they can scan through it and decide whether or not to approach you, rather than have to stand right in your personal space to see your poster. Print pieces of your poster on A4 at 100% scaling before sending it off to the official printers - make sure that you can easily read the text from 2 meters away. Importantly, ***make sure that figure text and symbols (axes titles and labels, legends, map points and labels, etc) are also readable from 2 meters away!*** (Note: It's ok to use a smaller font for the works cited list and acknowledgements.)

4) **Carefully consider placement!** Your poster will likely be stuck to a board or wall with the top of the poster a little above the average person's eye level (so, let's say about 175-185 cm up). As such, people's attention will naturally go towards text and graphics that are higher on the poster - so put the important information there! Whatever layout you choose for your poster, make sure the **Main question/hypothesis** and/or the **Answer/Conclusion** are near the top of your poster, around average eye level. Nitty-gritty details (often methods, definitely works cited and acknowledgements) should go nearer/at the bottom.

5) **Make it aesthetically pleasing!** Having an attractive overall design and a cohesive color scheme will draw more of your audience to your poster, and make it easier for people to focus on. Don't clutter your poster with distracting visuals, don't use a whole bunch of different fonts, do use a solid background color (not a busy picture), do use high contrast background & foreground colors that are easy to see, and do check that your colors are color-blind-friendly. Think carefully about the layout of your poster, how many columns, how much 'white-space' in between elements, etc. Align and distribute elements evenly.

6) **Get feedback!** Before you send your poster to the printers, get feedback from your friends, colleagues, and collaborators! Print out a scaled-down A4 version of your poster to show others, and ask people for feedback. Or, gather a few people together and project the digital copy of your poster and solicit feedback this way. Just like with scientific writing and scientific talks, [feedback is your friend](#FF)!

7) **Practice your pitch!** While developing your poster, think about how you will present your study to interested passers by. Once somebody has been reeled in by your attractive and concise poster, you'll want to be able to explain your research succinctly, using your poster as a visual aide. Develop a mini talk, about 60-90 seconds long, in synchrony with your poster. Once your poster is printed, practice practice practice, and ask for feedback on this too! Take it from me, nothing is more awkward than when a senior scientist who you are really keen to meet comes by your poster and says "So tell me about your study" and since you are not prepared, you give them a chaotic panic-fueled 5-minute monologue which then causes them to flee, somehow knowing less about your research than they did when they arrived.
