---
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```


# Imprint/Provider Identification {-}

*The following provides mandatory data concerning the provider of this website, obligations with regard to data protection, as well as other important legal references involving the Internet site of Alison Ashbury as required by German law.*

### Provider {-}
The provider of this Internet site within the legal meaning of the term is Alison Ashbury.

### Work Address {-}
Max Planck Institute of Animal Behavior <br>
Am Obstberg 1 <br>
78315 Radolfzell <br>
Germany <br>

Email: aashbury@ab.mpg.de


### Liability for Contents of Online Information {-}
As the provider of contents in accordance with Section 7 Paragraph 1 of the Tele-Media Law, Alison Ashbury shall be responsible for any contents which she makes available for use in accordance with general legal provisions. Alison Ashbury makes every effort to provide timely and accurate information on this website. Nevertheless, errors and inaccuracies cannot be completely ruled out. Therefore, Alison Ashbury does not assume any liability for the relevance, accuracy, completeness or quality of the information provided. Alison Ashbury shall not be liable for damage of a tangible or intangible nature caused directly or indirectly through the use or failure to use the information offered and/or through the use of faulty or incomplete information unless she is verifiably culpable of intent or gross negligence. The same shall apply to any downloadable software or resources available free of charge. Alison Ashbury reserves the right to modify, supplement, or delete any or all of the information offered on this website, or to temporarily or permanently cease publication thereof without prior and separate notification.

### Links to Internet Sites of Third Parties {-}
This website includes links to external pages. The respective provider shall be responsible for the contents of any linked external pages. In establishing the initial link, Alison Ashbury has reviewed the respective external content in order to determine whether such link entailed possible civil or criminal responsibility. However, a constant review of linked external pages is unreasonable without concrete reason to believe that a violation of the law may be involved. If Alison Ashbury determines such or it is pointed out by others that an external offer to which it is connected via a link entails civil or criminal responsibility, then Alison Ashbury will immediately eliminate any link to this offer. Alison Ashbury expressly dissociates herself from such contents.

### Copyright {-}
The layout, graphics employed and any other contents on this page are protected by copyright law. <br>
© Alison M Ashbury (unless explicitly stated otherwise). All right reserved. 

The EAS logo in the bottom left corner: <br>
© Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V., Munich. All rights reserved.